### ISSUE TITLE
"ddev start" fails with "Cannot destructure property 'nuxt' of 'this'"

### ISSUE THREAD

**Issue by KHBerlin** [TYPO3-Headless/pwa-demo#65]
Following the installation steps from the docs, `ddev start` fails with the following error:

```
yarn run v1.22.19
$ nuxt build
ℹ Using default Tailwind CSS file from runtime/tailwind.css                                                                           nuxt:tailwindcss 13:51:54

 ERROR  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                               13:51:54

  at postcss8Module (node_modules/@nuxt/postcss8/dist/index.js:15:10)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
```

It is probably related to new `nuxt/kit` versions, see https://github.com/nuxt/nuxt.js/issues/10840

**Comment by mileo** [comment]
Same here

**Comment by on3d3v** [comment]
i am also getting the same error please help

**Comment by mercs600** [comment]
Thank you guys, we are working on that

**Comment by mercs600** [comment]
@KHBerlin you were right, issue was related with nuxt/kit and tailwind module. It's fixed now. 
Please remove your ddev data or `front/node_modules` and `front/yarn.lock` before ddev restart
